version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_server
    ports:
      - "3312:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kleanarch
    volumes:
      - ./.data:/var/lib/mysql